### PR TITLE
Create oauth bloc

### PR DESCRIPTION
**Pull request by alexrintt**

### CODE REVIEW

**Comment by riccardocescon** [comment]
@alexrintt why you decided to use Cubit instead of Bloc?

**Comment by alexrintt** [comment]
> @alexrintt why you decided to use Cubit instead of Bloc?

Simplicity: less boilerplate code, less classes, same result.

**Comment by riccardocescon** [comment]
@alexrintt is the last commit basically a merge with the [chesskit] branch? if so we can merge this to the main and start another branch for the implementations, and remove the chesskit branch

**Comment by riccardocescon** [comment]
Updated the AuthState with freezed states, give it a look, what do you think about working this way for cubit states?

**Comment by alexrintt** [comment]
seems unnecessary use of code generation, but i think it works.

**Comment by riccardocescon** [comment]
> seems unnecessary use of code generation, but i think it works.

We use Freezed in order to get that <event>.map in order to analyze the result instead of adding a lot of code Just to 'filter' the event

**Comment by riccardocescon** [comment]
So Will we be using this approach? Can we implement this ok the code already written and merge?

**Pull request merged**
